# Phase 1 - Week 1 - Day 1 PM - Machine Learning Problem Framing - Inference

# Import Library

In [1]:
# Import libraries

import pickle
import json
import pandas as pd
import numpy as np

# Load Model

In [2]:
# Load all files

with open('model_lin_reg.pkl', 'rb') as file_1:
  model_lin_reg = pickle.load(file_1)

with open('model_scaler.pkl', 'rb') as file_2:
  model_scaler = pickle.load(file_2)

with open('model_encoder.pkl','rb') as file_3:
  model_encoder = pickle.load(file_3)

with open('list_num_cols.txt', 'r') as file_4:
  list_num_cols = json.load(file_4)

with open('list_cat_cols.txt', 'r') as file_5:
  list_cat_cols = json.load(file_5)

# Inferencing

In [3]:
# Create a new data
# Use all columns not just the results of feature selection

data_inf = {
    'Name': 'John Doe',
    'Age': 26,
    'Height': 172,
    'Weight': 70,
    'Price': 0,
    'AttackingWorkRate': 'High',
    'DefensiveWorkRate': 'Medium',
    'PaceTotal': 60,
    'ShootingTotal': 60,
    'PassingTotal': 70,
    'DribblingTotal': 60,
    'DefendingTotal': 60,
    'PhysicalityTotal':60
}

data_inf = pd.DataFrame([data_inf])
data_inf

,Name,Age,Height,Weight,Price,AttackingWorkRate,DefensiveWorkRate,PaceTotal,ShootingTotal,PassingTotal,DribblingTotal,DefendingTotal,PhysicalityTotal
0,John Doe,26,172,70,0,High,Medium,60,60,70,60,60,60

In [4]:
# Split between numerical columns and categorical columns

data_inf_num = data_inf[list_num_cols]
data_inf_cat = data_inf[list_cat_cols]
data_inf_num

,Age,Height,Weight,Price,PaceTotal,ShootingTotal,PassingTotal,DribblingTotal,DefendingTotal,PhysicalityTotal
0,26,172,70,0,60,60,70,60,60,60

In [5]:
# Feature Scaling and Feature Encoding

## Feature Scaling
data_inf_num_scaled = model_scaler.transform(data_inf_num)

## Feature Encoding
data_inf_cat_encoded = model_encoder.transform(data_inf_cat)

## Concate
data_inf_final = np.concatenate([data_inf_num_scaled, data_inf_cat_encoded], axis=1)
data_inf_final

array([[0.26315789, 0.33333333, 0.3442623 , 0.        , 0.46376812,
        0.55263158, 0.66176471, 0.51515152, 0.5974026 , 0.49206349,
        2.        , 1.        ]])

In [6]:
# Predict using Linear Regression

y_pred_inf = model_lin_reg.predict(data_inf_final)
y_pred_inf

array([64.26575671])